### ISSUE TITLE
how to restore my settings?

### ISSUE THREAD

**Issue by spurdow** [colbycheeze/dotfiles#1]
i tried your setup installation. but im having problems.

**Comment by colbycheeze** [comment]
What issues did you run into / how far did you get?
Depending on what you want to 'undo' you can look at what was done within the setup folder such as symlinking the files in your dotfiles folder, or installing various programs with brew.

**Comment by joseplata** [comment]
Hey @colbycheeze I'm now getting 

`N/A: version "N/A" is not yet installed`
`You need to run "nvm install N/A" to install it before using it.`


Every time I start tmux. Any idea how to fix this??

Thanks!

**Comment by colbycheeze** [comment]
@joseplata Sounds like a version of node is trying to run that is not installed or something.
you might check `node -v` and/or do a `nvm install node` and do the `nvm alias default node`

https://github.com/colbycheeze/dotfiles/blob/master/setup/applications.sh#L87-L102
This is the part that sets up node...if you ran the setup and already had node installed or a version manager running perhaps it conflicted somehow.

Worst case scenario, just uninstall node / nvm and then rerun that one piece of script there to get it setup again.

**Comment by joseplata** [comment]
@colbycheeze Yes! I was about to say, I just ran `nvm install --lts && nvm use --lts` and it fixed it all. Thanks for this!

**Comment by spurdow** [comment]
oh sorry for late reply, I already fixed this, I reset my config using other configs and copied some of your config.

**Comment by colbycheeze** [comment]
one last reminder for you guys, I just updated my Readme also, but if you copied over all of my dotfiles make sure to update the bottom of the `gitconfig`to be your own user info, so that your commits don't look like I made them :)
