### ISSUE TITLE
Changing panes away from vim

### ISSUE THREAD

**Issue by tsandstr** [colbycheeze/dotfiles#2]
When changing away from a vim pane and to, say, a bash pane, the <C-j/k/h/l> shortcuts don't work. They are sent to vim itself, even when you are currently in a split on the edge of vim's pane.

**Comment by colbycheeze** [comment]
I'm away from my main PC until after the 8th so I can't look into it until then. It was working for me last I checked, so there might be something odd going on (unless something got changed that I am not aware of)

**Comment by colbycheeze** [comment]
I've got my home setup running again and everything works fine. It's possible you are missing some of the config.

This is the Tmux config code you need in `tmux.conf`: https://github.com/colbycheeze/dotfiles/blob/master/tmux.conf#L74-L80

It's also possible you will need this in your `vimrc`:
https://github.com/colbycheeze/dotfiles/blob/master/vimrc#L107-L115
