### ISSUE TITLE
<C-J> back into tmux from vim

### ISSUE THREAD

**Issue by danielcliffordmiller** [colbycheeze/dotfiles#4]
I stumbled across your 'vim as an IDE' youtube video and thought I would use your dotfiles to inspire some modifications in my own - so I copied some of them.

The ability to use the CTRL-{H,J,K,L} keys to move around seamlessly was really neat, but I did not see any way to moved from vim back out into another tmux pane without have to use C-a J.

So I wrote a vim plugin to check if you are `<c-j>`ing off an edge vim-window into tmux and if so, it will make the transition for you.

I thought you may have some use for this.

[https://github.com/danielcliffordmiller/vim-tmux-integration](https://github.com/danielcliffordmiller/vim-tmux-integration)

**Comment by colbycheeze** [comment]
Hmm, mine actually works already. It's been a while since I set this up but I believe this is the bit that handles it. Would you mind verifying if it works for you as well?

https://github.com/colbycheeze/dotfiles/blob/master/vimrc#L107-L115

**Comment by colbycheeze** [comment]
It's also possible that these help? (Again, been a long time since I've set up some of my config and things just work lol)

https://github.com/colbycheeze/dotfiles/blob/master/vimrc.bundles#L28-L32

**Comment by danielcliffordmiller** [comment]
I confess I did not actually run your dot files verbatim.  I only looked at your vimrc and tmux.conf, but  not the vim plugins you were bringing in.
That vim-tmux-navigation plugin appears to do more or less what mine does.  So nevermind!
