### ISSUE TITLE
Installation is not running fine

### ISSUE THREAD

**Issue by rogoit** [colbycheeze/dotfiles#5]
Also it installs too much. How can i revert it?

**Comment by colbycheeze** [comment]
What did not run fine in the install? Could you clarify a bit more so I can better help. Also the script uses brew to install apps. You can view and customize to your liking, or uninstall via brew.

**Comment by rogoit** [comment]
I think the problem is that i want to have a better vim but get everything.

zsh
global git settings
spotify

and much more that i do not need. I love yout videos and stuff. I thought you had a simple vimrc file. I setup my mac new and clean and lost it. So i installed this but makes so much stuff outside vim and tmux. 

That would be easier when you write this in the readme. I thought it was a simple vim ide maker. But it is your global system.

Sorry for the issue, but yesterday i had a bit panic.

**Comment by colbycheeze** [comment]
No problem, hope you are able to get things back to normal. I have a comment in the README about forking / customizing but I should likely write it bolder at the top like "YO DONT RUN THIS W/O KNOWING WHAT IT DOES!" haha

Hope you got everything fixed!
